//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMLINFO.SisCadastro.Web.Ui.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadAlunoPABLO
    {
        public int ID_ALUNO { get; set; }
        public string COD_MATRICULA { get; set; }
        public string NOME { get; set; }
        public System.DateTime DATA_NASCIMENTO { get; set; }
    }
}
